OPERAND_SIGIL                   =   '*'
UNARY_OP_SIGIL                  =   '='
BINARY_OP_SIGIL                 =   '/'
SIMULTANEOUS_OP_FLAG            =   '+'
PARTITION_OP_SIGIL              =   '<'
PARTITION_A_PORTION_FLAG        =   '%'
PARTITION_B_PORTION_FLAG        =   '_'
STORED_OPERAND_SIGIL            =   '>'
DISCARD_OP_SIGIL                =   '!'
VARIANT_LIST_START_SIGIL        =   '['
VARIANT_LIST_SEPARATOR          =   '|'
VARIANT_LIST_CLOSE_SIGIL        =   ']'
VARIANT_TAG_LIST_SEPARATOR      =   ','
PSEUDO_OPERAND_FLAG             =   ':'
VARIANT_TAG_SIGIL               =   '#'
MODIFIER_SIGIL                  =   ','
ANNOTATION_SIGIL                =   ';'
ALPHA_CHARS                     =   "A-Za-z"
NZ_DIGIT_CHARS                  =   "1-9"
DIGIT_CHARS                     =   "0" + NZ_DIGIT_CHARS
PHRASE_CHARS                    =   "-' \"" + ALPHA_CHARS
STRING_CHARS                    =   PHRASE_CHARS + DIGIT_CHARS + "[]#\."